database_name     = "my_db" 
database_user     = "MDrachevskii"
database_password = "123w123w"
region            = "eu-central-1"  
key_name          = "francfurt" // key name for ec2
instance_type     = "t2.micro" 
ami               = "ami-05d34d340fb1d89e5"
#access_key       =
#secret_key       = 