variable "database_name" {}
variable "database_password" {}
variable "database_user" {}
variable "region" {}
variable "instance_type" {}
variable "key_name" {}
variable "ami" {}
variable "access_key" {}
variable "secret_key" {}